### ISSUE TITLE
HELP. I CAN'T CREATE CLOUDFORMATION STACK USING FILE PROVIDED

### ISSUE THREAD

**Issue by Choice-Jay** [aws-samples/aws-bookstore-demo-app#24]
When creating an AWS CloudFormation Stack using the mybookstore file provided or the link provided, I keep getting an error that said rollback_complete with an X mark in front. It is constantly failing to create the stack.

**Comment by triggan** [comment]
Very likely related to #27

**Comment by expresslaw** [comment]
More likely related to #29 (https://github.com/aws-samples/aws-bookstore-demo-app/issues/29). Choice-Jay, are you getting an authentication message regarding code in an S3 bucket? "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for fsd-aws-wildrydes-us-west-2/aws-serverless-codecommit-seeder.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied...." If that's the case then it appears to be due to whoever owns the fsd-aws-wildrydes/<region>/ bucket altering GetObject access permissions on this file.

**Comment by sebastienpiette** [comment]
No update yet  ?

**Comment by triggan** [comment]
Both issues #27 and #29 have been resolved and the stack has seen significant updates recently.  Closing out this issue.
